name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: echo github.ref
        run: echo ${{ github.ref }}

      - name: checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: install dependencies
        run: |
          npm ci

      - name: current Time
        run: |
          date

      - name: test
        run: |
          npm run lint:unused